# Generated by Django 4.1.4 on 2023-01-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests', unique=True),
        ),
    ]
