# Generated by Django 4.1.4 on 2023-01-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_calender_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='calender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.calender'),
            preserve_default=False,
        ),
    ]
