# Generated by Django 4.1.4 on 2023-01-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_test_calender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='calender',
        ),
    ]
