# Generated by Django 4.1.4 on 2023-01-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_test_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
