# Generated by Django 4.1.4 on 2023-01-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_calender_contest_alter_calender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests', unique=True),
        ),
    ]
