# Generated by Django 4.1.4 on 2023-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_calender_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
